--------------------------------------------------------------------------------
--  Sistem Permohonan Capaian Sistem (MBSP)
--  Skema Oracle (12c ke atas — guna lajur IDENTITY)
--
--  Nota:
--   * Asal sistem guna SQLite. Jenis data telah dipetakan ke Oracle:
--       INTEGER PRIMARY KEY AUTOINCREMENT  -> NUMBER GENERATED BY DEFAULT AS IDENTITY
--       TEXT                               -> VARCHAR2 (atau CLOB utk teks panjang)
--       DATETIME                           -> TIMESTAMP
--       status 0/1                         -> NUMBER(1) + CHECK
--   * Lajur tarikh guna DEFAULT SYSTIMESTAMP. Jika mahu waktu Malaysia (+8),
--     tetapkan zon masa sesi/pangkalan data, atau guna:
--       DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Kuala_Lumpur' AS TIMESTAMP)
--   * Jalankan keseluruhan skrip ini dalam SQL*Plus / SQL Developer / sqlcl.
--------------------------------------------------------------------------------

--==============================================================================
--  BAHAGIAN 0 : (Pilihan) Buang jadual sedia ada — selamat untuk jalankan semula
--  Abaikan jika ini pemasangan baharu.
--==============================================================================
BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'AUDIT_TRAIL','PERMOHONAN_SISTEM','PERMOHONAN',
      'PENYEMAK','PERANAN','SISTEM_ADMIN','JABATAN_PENGARAH','SENARAI_SISTEM',
      'GAJI','USERS'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

--==============================================================================
--  1. USERS — akaun log masuk
--==============================================================================
CREATE TABLE users (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR2(50)  NOT NULL,
    password       VARCHAR2(255) NOT NULL,          -- hash password_hash() PHP
    role           VARCHAR2(20)  NOT NULL,          -- pemohon, pengarah_jab, pengarah_jtik, admin_it, penyemak_it
    nama           VARCHAR2(150),
    no_kakitangan  VARCHAR2(30),
    jawatan        VARCHAR2(120),
    gred_jawatan   VARCHAR2(20),
    jabatan        VARCHAR2(120),
    telefon        VARCHAR2(30),
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_users        PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username)
);

--==============================================================================
--  2. GAJI — sumber rasmi data kakitangan (rujukan semakan)
--==============================================================================
CREATE TABLE gaji (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    no_kakitangan  VARCHAR2(30)  NOT NULL,
    nama           VARCHAR2(150),
    jawatan        VARCHAR2(120),
    gred_jawatan   VARCHAR2(20),
    jabatan        VARCHAR2(120),
    telefon        VARCHAR2(30),
    status         VARCHAR2(20) DEFAULT 'AKTIF',
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_gaji            PRIMARY KEY (id),
    CONSTRAINT uq_gaji_nokakitangan UNIQUE (no_kakitangan)
);

--==============================================================================
--  3. SENARAI_SISTEM — senarai sistem yang boleh dipohon
--     (id_sistem ditetapkan secara manual 1..N, bukan auto)
--==============================================================================
CREATE TABLE senarai_sistem (
    id_sistem    NUMBER        NOT NULL,
    nama_sistem  VARCHAR2(200) NOT NULL,
    kod_sistem   VARCHAR2(40),
    status       NUMBER(1) DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_senarai_sistem PRIMARY KEY (id_sistem),
    CONSTRAINT ck_sistem_status  CHECK (status IN (0,1))
);

--==============================================================================
--  4. JABATAN_PENGARAH — pemetaan jabatan -> pengarah (auto-routing)
--==============================================================================
CREATE TABLE jabatan_pengarah (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    kod_jabatan    VARCHAR2(120) NOT NULL,
    nama_pengarah  VARCHAR2(150),
    no_pekerja     VARCHAR2(30),
    status         NUMBER(1) DEFAULT 1 NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT pk_jabatan_pengarah PRIMARY KEY (id),
    CONSTRAINT ck_jabpeng_status   CHECK (status IN (0,1))
);

--==============================================================================
--  5. SISTEM_ADMIN — pemetaan sistem -> Admin IT bertanggungjawab
--==============================================================================
CREATE TABLE sistem_admin (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_sistem    NUMBER        NOT NULL,
    no_pekerja   VARCHAR2(30),
    nama_admin   VARCHAR2(150),
    status       NUMBER(1) DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_sistem_admin   PRIMARY KEY (id),
    CONSTRAINT ck_sisadmin_status CHECK (status IN (0,1)),
    CONSTRAINT fk_sisadmin_sistem FOREIGN KEY (id_sistem)
        REFERENCES senarai_sistem (id_sistem)
);

--==============================================================================
--  6. PENYEMAK — daftar penyemak IT (semakan dalaman kerja Admin IT)
--==============================================================================
CREATE TABLE penyemak (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nama         VARCHAR2(150) NOT NULL,
    jawatan      VARCHAR2(120),
    no_pekerja   VARCHAR2(30),
    status       NUMBER(1) DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_penyemak       PRIMARY KEY (id),
    CONSTRAINT ck_penyemak_status CHECK (status IN (0,1))
);

--==============================================================================
--  6b. PERANAN — senarai peranan + had kuasa (0/1 bagi setiap fungsi)
--==============================================================================
CREATE TABLE peranan (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    kod          VARCHAR2(40)  NOT NULL,
    nama         VARCHAR2(120) NOT NULL,
    penyedia     NUMBER(1) DEFAULT 0,
    pengemaskini NUMBER(1) DEFAULT 0,
    penyemak     NUMBER(1) DEFAULT 0,
    pelapor      NUMBER(1) DEFAULT 0,
    pengesah     NUMBER(1) DEFAULT 0,
    pelulus      NUMBER(1) DEFAULT 0,
    penghapus    NUMBER(1) DEFAULT 0,
    status       NUMBER(1) DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_peranan      PRIMARY KEY (id),
    CONSTRAINT uq_peranan_kod  UNIQUE (kod),
    CONSTRAINT ck_peranan_status CHECK (status IN (0,1))
);

--==============================================================================
--  7. PERMOHONAN — rekod utama permohonan capaian
--==============================================================================
CREATE TABLE permohonan (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    no_rujukan           VARCHAR2(40),
    user_id              NUMBER        NOT NULL,
    nama                 VARCHAR2(150) NOT NULL,
    no_kakitangan        VARCHAR2(30)  NOT NULL,
    jawatan              VARCHAR2(120) NOT NULL,
    gred_jawatan         VARCHAR2(20)  NOT NULL,
    jabatan              VARCHAR2(120) NOT NULL,
    telefon              VARCHAR2(30)  NOT NULL,
    tujuan               VARCHAR2(20)  NOT NULL,        -- baru / kemaskini / pembatalan
    status               VARCHAR2(30) DEFAULT 'MENUNGGU_PENGARAH_JAB' NOT NULL,
    tarikh_pemohon       TIMESTAMP DEFAULT SYSTIMESTAMP,
    pengarah_jab_id      NUMBER,
    nama_pengarah_jab    VARCHAR2(150),
    tarikh_pengarah_jab  TIMESTAMP,
    pengarah_jtik_id     NUMBER,
    kelulusan_jtik       VARCHAR2(30),                  -- DILULUSKAN / TIDAK_DILULUSKAN
    alasan_jtik          VARCHAR2(1000),
    tarikh_jtik          TIMESTAMP,
    it_pemberi_nama      VARCHAR2(150),
    it_pemberi_cop       VARCHAR2(150),
    it_penyemak_nama     VARCHAR2(150),
    it_penyemak_cop      VARCHAR2(150),
    tarikh_it            TIMESTAMP,
    tarikh_semakan       TIMESTAMP,
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_permohonan       PRIMARY KEY (id),
    CONSTRAINT uq_permohonan_rujuk UNIQUE (no_rujukan),
    CONSTRAINT fk_permohonan_user  FOREIGN KEY (user_id) REFERENCES users (id)
);

--==============================================================================
--  8. PERMOHONAN_SISTEM — sistem yang dipohon bagi setiap permohonan
--     (penyedia..penghapus = had kuasa, 0/1)
--==============================================================================
CREATE TABLE permohonan_sistem (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    permohonan_id  NUMBER        NOT NULL,
    bil            NUMBER        NOT NULL,        -- = id_sistem dalam senarai_sistem
    nama_sistem    VARCHAR2(200) NOT NULL,
    catatan        VARCHAR2(500),
    peranan_sistem VARCHAR2(40) DEFAULT '',
    penyedia       NUMBER(1) DEFAULT 0,
    pengemaskini   NUMBER(1) DEFAULT 0,
    penyemak       NUMBER(1) DEFAULT 0,
    pelapor        NUMBER(1) DEFAULT 0,
    pengesah       NUMBER(1) DEFAULT 0,
    pelulus        NUMBER(1) DEFAULT 0,
    penghapus      NUMBER(1) DEFAULT 0,
    CONSTRAINT pk_permohonan_sistem PRIMARY KEY (id),
    CONSTRAINT fk_psistem_permohonan FOREIGN KEY (permohonan_id)
        REFERENCES permohonan (id)
);

--==============================================================================
--  9. AUDIT_TRAIL — jejak tindakan
--==============================================================================
CREATE TABLE audit_trail (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    permohonan_id  NUMBER,
    processed_by   VARCHAR2(30),
    processed_name VARCHAR2(150),
    action         VARCHAR2(50),
    catatan        VARCHAR2(1000),
    processed_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_audit_trail      PRIMARY KEY (id),
    CONSTRAINT fk_audit_permohonan FOREIGN KEY (permohonan_id)
        REFERENCES permohonan (id)
);

--==============================================================================
--  INDEKS (prestasi carian / routing)
--==============================================================================
CREATE INDEX ix_permohonan_status   ON permohonan (status);
CREATE INDEX ix_permohonan_user     ON permohonan (user_id);
CREATE INDEX ix_permohonan_jabatan  ON permohonan (jabatan);
CREATE INDEX ix_psistem_permohonan  ON permohonan_sistem (permohonan_id);
CREATE INDEX ix_psistem_bil         ON permohonan_sistem (bil);
CREATE INDEX ix_sisadmin_pekerja    ON sistem_admin (no_pekerja);
CREATE INDEX ix_jabpeng_pekerja     ON jabatan_pengarah (no_pekerja);
CREATE INDEX ix_audit_permohonan    ON audit_trail (permohonan_id);

COMMIT;
